-- Database: CENSOARBOLEO2022

-- DROP DATABASE "CENSOARBOLEO2022";´


CREATE TABLE IF NOT EXISTS ARBOL (
	id SERIAL,
	arbolId  INT PRIMARY KEY NOT NULL,
	codigo   TEXT    NOT NULL,
	placa    TEXT     NOT NULL,
	qrcode   CHAR(128),
	barrio   TEXT   NOT NULL,
	comuna   CHAR(2) NOT NULL,
	latitud DECIMAL(11) NOT NULL,
	longitud DECIMAL(11) NOT NULL,
	norte DECIMAL(11) NOT NULL,
	este DECIMAL(11) NOT NULL,
	nombre_comun TEXT NOT NULL,
	familia TEXT NOT NULL, 
	genero TEXT NOT NULL,
	especie TEXT NOT NULL, 
	tipo_vegetacion TEXT NOT NULL, 
	madurez TEXT NOT NULL, 
	area DECIMAL(11) NOT NULL,
	perimetro DECIMAL(11) NOT NULL,
	hito TEXT NOT NULL,
	estado_conservacion TEXT NOT NULL,
	intervencion TEXT NOT NULL,
	cobertura TEXT NOT NULL,	
	confinamiento INT NOT NULL, 
	dist_confinamiento DECIMAL, 
	emplazamiento TEXT NOT NULL,
	foto1 TEXT NOT NULL, 
	foto2 TEXT NOT NULL, 
	foto3 TEXT , 
	foto4 TEXT ,
	observaciones TEXT, 
	estado TEXT NOT NULL, 
	fecha_creado DATE NOT NULL,
	modificadopor TEXT NOT NULL,
	actualizado  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	version_fecha DATE NOT NULL
);


CREATE TABLE IF NOT EXISTS DASOMETRIA (
	id SERIAL, 
	arbolId INT NOT NULL, 
	codigo TEXT NOT NULL, 
	fuste TEXT NOT NULL, 
	numtallos INT  NOT NULL, 
	cap DECIMAL, 
	cap1 DECIMAL,
	cap2 DECIMAL,
	cap3 DECIMAL,
	cap4 DECIMAL,
	cap5 DECIMAL,
	dap DECIMAL,
	altura_fuste DECIMAL NOT NULL, 
	altura_arbol DECIMAL NOT NULL, 
	diacopa_mayor DECIMAL NOT NULL,
	diacopa_menor DECIMAL NOT NULL,
	inclinacion TEXT NOT NULL,
	orientacion DECIMAL NOT NULL,
	tiporaiz TEXT NOT NULL,
	copaviva DECIMAL NOT NULL,
	copaausente DECIMAL NOT NULL,
	saludcopa DECIMAL NOT NULL,
	expcopaluz DECIMAL NOT NULL,
	tipocopa TEXT NOT NULL,
	diametro_ramas TEXT NOT NULL,
	comentarios TEXT, 
	fecha_creado DATE NOT NULL,
	modificadopor TEXT NOT NULL,
	actualizado  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	version_fecha DATE NOT NULL
	);
	
	
CREATE TABLE IF NOT EXISTS ESTADO_FITOSANITARIO (
	id SERIAL,
	arbolId INT NOT NULL, 
	codigo TEXT NOT NULL, 
	vitalidad TEXT NOT NULL,
	tiposafectacion TEXT NOT NULL,
	mecanica_fuste TEXT NOT NULL,
	mecanica_copa TEXT NOT NULL,
	mecanica_raiz TEXT NOT NULL,
	mecanica_f_anillado INT NOT NULL,
	mecanica_f_heridas INT NOT NULL,
	mecanica_f_quemaduras INT NOT NULL,
	mecanica_c_heridas INT NOT NULL,
	mecanica_c_quemaduras INT NOT NULL,
	mecanica_r_heridas INT NOT NULL,
	mecanica_r_quemaduras INT NOT NULL,
	biologica_fuste TEXT, 
	biologica_copa TEXT, 
	biologica_raiz TEXT, 
	biologica_f_perfobarrenado INT NOT NULL,
	biologica_f_necrosis INT NOT NULL,
	biologica_f_descortezado INT NOT NULL,
	biologica_f_tumores INT NOT NULL, 
	biologica_c_defoliacion INT NOT NULL, 
	biologica_c_clorosis INT NOT NULL, 
	biologica_c_minado INT NOT NULL,
	biologica_c_necrosis INT NOT NULL,
	biologica_c_parasitas INT NOT NULL,
	biologica_r_necrosis INT NOT NULL,
	antropica_fuste TEXT, 
	antropica_copa TEXT, 
	antropica_raiz TEXT, 
	antropica_f_poda  INT NOT NULL, 
	antropica_f_escombros INT NOT NULL, 
	antropica_c_poda INT NOT NULL, 
	antropica_c_contamatmosferica INT NOT NULL, 
	antropica_r_poda INT NOT NULL, 	
	antropica_r_escombros INT NOT NULL, 
	general_f_sano INT NOT NULL, 
	general_c_sano INT NOT NULL, 
	general_r_sano INT NOT NULL, 
	comentarios TEXT,
	fecha_creado TIME NOT NULL,
	modificadopor TEXT NOT NULL,
	actualizado  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	version_fecha DATE NOT NULL
	);	
	
CREATE TABLE IF NOT EXISTS VULNERABILIDAD (
	id SERIAL,
	arbolId INT NOT NULL, 
	codigo TEXT NOT NULL,
	personas INT NOT NULL,
	vehiculos INT NOT NULL,
	construcciones INT NOT NULL,
	redes_aereas INT NOT NULL,
	comentarios TEXT,
	fecha_creado DATE NOT NULL,
	modificadopor TEXT NOT NULL,
	actualizado  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	version_fecha DATE NOT NULL
	);
	

CREATE TABLE IF NOT EXISTS INTERVENCIONES(
	id INT NOT NULL,
	arbolId INT NOT NULL, 
	codigo TEXT NOT NULL,
	control_fitosanitario INT NOT NULL,
	erradicacion INT NOT NULL,
	poda_aclareo INT NOT NULL,
	poda_control INT NOT NULL,
	poda_equilibrio INT NOT NULL,
	poda_formacion INT NOT NULL,
	poda_limpieza  INT NOT NULL,
	poda_realce  INT NOT NULL,
	poda_ramas_laterales INT NOT NULL,
	poda_ramas_secas  INT NOT NULL,
	poda_sanitaria INT NOT NULL,
	poda_reduccion_altura INT NOT NULL,
	poda_energizado INT NOT NULL,
	poda_despeje_redes_transplante INT NOT NULL,
	transplante INT NOT NULL,
	eliminar_pisoduro INT NOT NULL,
	porque_tala TEXT NOT NULL,
	comentarios TEXT,
	fecha_creado DATE NOT NULL,
	modificadopor TEXT NOT NULL,
	actualizado  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	version_fecha DATE NOT NULL
);
	
	
CREATE TABLE IF NOT EXISTS IDENTIFICACION_TAXONOMICA(
	id SERIAL,
	nombre_comun TEXT NOT NULL,
	familia  TEXT NOT NULL,
	genero TEXT NOT NULL,
	especie TEXT NOT NULL,
	sinonimo_especie TEXT,
	sinonimo_ncomun  TEXT,
	origen TEXT,
	condicion TEXT,
	habito_crecimiento TEXT,
	altura_maxima  TEXT NOT NULL,
	dap_maximo TEXT NOT NULL,
	tasa_crecimiento TEXT,
	longevidad INT NOT NULL, 
	tipo_vegetacion TEXT NOT NULL, 
	tipo_copa TEXT NOT NULL, 
	descripcion TEXT,
	version_fecha DATE NOT NULL 
);