# Generated by Django 4.1.3 on 2023-01-04 17:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('cedula_usuario', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('foto', models.ImageField(default='fotos_usuarios/image-default.png', upload_to=usuarios.models.Usuario._generar_ruta_imagen)),
                ('direccion', models.TextField()),
                ('telefono', models.BigIntegerField()),
                ('rol', models.TextField()),
                ('Grupo', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'ordering': ['first_name'],
                'permissions': (('Administrador', 'Permisos de Administrador'), ('Censista', 'Permisos de Censista'), ('Supervisor', 'Permisos de Supervisor'), ('SuperForestal', 'Permisos de Supervisor Forestal')),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
